AWSTemplateFormatVersion: 2010-09-09
Description: Udacity project 2 - Nickson Kipkorir


Parameters:
  EnvironmentName:
    Description: Environment name for all the resources
    Type: String

  VpcCIDR:
    Description: Ip adress range CIDR 
    Type: String
    Default:  10.0.0.0/16

  PublicSubnet1CIDR:
    Description: Availabity zone one public Ip adress range CIDR 
    Type: String
    Default:  10.0.0.0/24

  PrivateSubnet1CIDR:
  Description: Availablity zone one private Ip adress range CIDR 
  Type: String
  Default:  10.0.2.0/24  

  PublicSubnet2CIDR:
    Description: Availablity zone two public  Ip adress range CIDR 
    Type: String
    Default:  10.0.1.0/24

  PrivateSubnet2CIDR:
    Description: Availablity zone two private Ip adress range CIDR 
    Type: String
    Default:  10.0.3.0/24    



Resources: 
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsHostnames: true
      Tags: 
        - Key: Name 
          Value: !Ref EnvironmentName

  PublicSubnet1: 
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: !Ref PublicSubnet1CIDR
      MapPublicIpOnLaunch: true
      Tags: 
          - Key: Name 
            Value: !Sub ${EnvironmentName} Public Subnet (AZ1)

  PrivateSubnet1: 
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: !Ref PrivateSubnet1CIDR
      MapPublicIpOnLaunch: false
      Tags: 
          - Key: Name 
            Value: !Sub ${EnvironmentName} Private Subnet (AZ1)
          

  PublicSubnet2: 
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      CidrBlock: !Ref PublicSubnet2CIDR
      MapPublicIpOnLaunch: true
      Tags: 
          - Key: Name 
            Value: !Sub ${EnvironmentName} Public Subnet (AZ2)

  
  PrivateSubnet2: 
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      CidrBlock: !Ref PrivateSubnet2CIDR
      MapPublicIpOnLaunch: false
      Tags: 
          - Key: Name 
            Value: !Sub ${EnvironmentName} Private Subnet (AZ2)   
          

